version: '2'

x-environment-vars: &environment-vars
    PYTHONUNBUFFERED: 1
    PYTHONIOENCODING: utf-8
    TERM: linux
    DEBUG: 'true'
    REDIS_URL: redis://redis:6379/6

services:

  app:
    build:
      context: .
      dockerfile: ./docker/Dockerfile
    environment:
      <<: *environment-vars
    ports:
      - "8000:8000"
    volumes:
      - .:/proj
    command: >
      sh -c "python -m code.app"
    stdin_open: true
    tty: true

  redis:
    image: redis:7.0-rc1-alpine

  currencies-worker:
    build:
      context: .
      dockerfile: ./docker/Dockerfile
    volumes:
      - .:/proj
      - /proj/bin
    environment:
      <<: *environment-vars
    command: python -m code.currencies
    stdin_open: true
    tty: true

networks:
  default:
    name: app-platform