---
apiVersion: v1
kind: ConfigMap
metadata:
  name: ${SERVICE_NAME}-credentials
  labels:
    app.kubernetes.io/name: ${SERVICE_NAME}
data:
  DATABASE_URL: "${DATABASE_URL}"
  REDIS_URL: "${REDIS_URL}"