---
apiVersion: v1
kind: Secret
metadata:
  name: ${SERVICE_NAME}-registry
  labels:
    app.kubernetes.io/name: ${SERVICE_NAME}
type: kubernetes.io/dockerconfigjson
data:
  .dockerconfigjson: ${REGISTRY_CREDENTIALS}